In [3]:
import pandas as pd

# Load the dataset
file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011/economic.csv'
economic_data = pd.read_csv(file_path)

# Display the first few rows of the dataset and the columns to understand its structure
economic_data.head(), economic_data.columns

(   date       geography geography code Rural Urban  \
 0  2011        Bank Top      E05001553       Total
 1  2011         Central      E05001554       Total
 2  2011  Cockerton East      E05001555       Total
 3  2011  Cockerton West      E05001556       Total
 4  2011         College      E05001557       Total

    Economic Activity: All categories: Economic activity; measures: Value  \
 0                                               2953
 1                                               3123
 2                                               3930
 3                                               2785
 4                                               2970

    Economic Activity: Economically active: Total; measures: Value  \
 0                                               2047
 1                                               2077
 2                                               2849
 3                                               1725
 4                                               2218

    Economic Activity: Economically active: Employee: Part-time; measures: Value  \
 0                                                398
 1                                                426
 2                                                635
 3                                                487
 4                                                423

    Economic Activity: Economically active: Employee: Full-time; measures: Value  \
 0                                               1148
 1                                               1131
 2                                               1696
 3                                                829
 4                                               1303

    Economic Activity: Economically active: Self-employed with employees: Part-time; measures: Value  \
 0                                                  8
 1                                                  7
 2                                                  8
 3                                                  6
 4                                                 17

    Economic Activity: Economically active: Self-employed with employees: Full-time; measures: Value  \
 0                                                 63
 1                                                 39
 2                                                 51
 3                                                 21
 4                                                 82

    Economic Activity: Economically active: Self-employed without employees: Part-time; measures: Value  \
 0                                                 51
 1                                                 42
 2                                                 49
 3                                                 35
 4                                                 74

    Economic Activity: Economically active: Self-employed without employees: Full-time; measures: Value  \
 0                                                104
 1                                                 92
 2                                                127
 3                                                 63
 4                                                133

    Economic Activity: Economically active: Unemployed; measures: Value  \
 0                                                215
 1                                                266
 2                                                161
 3                                                233
 4                                                103

    Economic Activity: Economically active: Full-time student; measures: Value  \
 0                                                 60
 1                                                 74
 2                                                122
 3                                                 51
 4                                                 83

    Economic Activity: Economically inactive: Total; measures: Value  \
 0                                                906
 1                                               1046
 2                                               1081
 3                                               1060
 4                                                752

    Economic Activity: Economically inactive: Retired; measures: Value  \
 0                                                392
 1                                                389
 2                                                561
 3                                                457
 4                                                448

    Economic Activity: Economically inactive: Student (including full-time students); measures: Value  \
 0                                                114
 1                                                113
 2                                                147
 3                                                 99
 4                                                132

    Economic Activity: Economically inactive: Looking after home or family; measures: Value  \
 0                                                122
 1                                                127
 2                                                151
 3                                                165
 4                                                 78

    Economic Activity: Economically inactive: Long-term sick or disabled; measures: Value  \
 0                                                213
 1                                                318
 2                                                181
 3                                                251
 4                                                 64

    Economic Activity: Economically inactive: Other; measures: Value
 0                                                 65
 1                                                 99
 2                                                 41
 3                                                 88
 4                                                 30                 ,
 Index(['date', 'geography', 'geography code', 'Rural Urban',
        'Economic Activity: All categories: Economic activity; measures: Value',
        'Economic Activity: Economically active: Total; measures: Value',
        'Economic Activity: Economically active: Employee: Part-time; measures: Value',
        'Economic Activity: Economically active: Employee: Full-time; measures: Value',
        'Economic Activity: Economically active: Self-employed with employees: Part-time; measures: Value',
        'Economic Activity: Economically active: Self-employed with employees: Full-time; measures: Value',
        'Economic Activity: Economically active: Self-employed without employees: Part-time; measures: Value',
        'Economic Activity: Economically active: Self-employed without employees: Full-time; measures: Value',
        'Economic Activity: Economically active: Unemployed; measures: Value',
        'Economic Activity: Economically active: Full-time student; measures: Value',
        'Economic Activity: Economically inactive: Total; measures: Value',
        'Economic Activity: Economically inactive: Retired; measures: Value',
        'Economic Activity: Economically inactive: Student (including full-time students); measures: Value',
        'Economic Activity: Economically inactive: Looking after home or family; measures: Value',
        'Economic Activity: Economically inactive: Long-term sick or disabled; measures: Value',
        'Economic Activity: Economically inactive: Other; measures: Value'],
       dtype='object'))

In [5]:
# Simplify the column names by removing repetitive and excessive wording
simplified_columns = {
    'date': 'Year',
    'geography': 'Area',
    'geography code': 'Area Code',
    'Rural Urban': 'Rural Urban',
    'Economic Activity: All categories: Economic activity; measures: Value': 'Total Population',
    'Economic Activity: Economically active: Total; measures: Value': 'Total Economically Active',
    'Economic Activity: Economically active: Employee: Part-time; measures: Value': 'Active Employees Part-time',
    'Economic Activity: Economically active: Employee: Full-time; measures: Value': 'Active Employees Full-time',
    'Economic Activity: Economically active: Self-employed with employees: Part-time; measures: Value': 'Active Self-Employed with Employees Part-time',
    'Economic Activity: Economically active: Self-employed with employees: Full-time; measures: Value': 'Active Self-Employed with Employees Full-time',
    'Economic Activity: Economically active: Self-employed without employees: Part-time; measures: Value': 'Active Self-Employed without Employees Part-time',
    'Economic Activity: Economically active: Self-employed without employees: Full-time; measures: Value': 'Active Self-Employed without Employees Full-time',
    'Economic Activity: Economically active: Unemployed; measures: Value': 'Unemployed',
    'Economic Activity: Economically active: Full-time student; measures: Value': 'Full-time Students',
    'Economic Activity: Economically inactive: Total; measures: Value': 'Total Economically Inactive',
    'Economic Activity: Economically inactive: Retired; measures: Value': 'Inactive Retired',
    'Economic Activity: Economically inactive: Student (including full-time students); measures: Value': 'Inactive Students',
    'Economic Activity: Economically inactive: Looking after home or family; measures: Value': 'Inactive Home or Family',
    'Economic Activity: Economically inactive: Long-term sick or disabled; measures: Value': 'Inactive Long-term Sick or Disabled',
    'Economic Activity: Economically inactive: Other; measures: Value': 'Inactive Other'
}

# Rename the columns
economic_data.rename(columns=simplified_columns, inplace=True)

# Display the new column names and the first few rows to check
economic_data.head(), economic_data.columns

# Save the cleaned and simplified dataset to a new CSV file
new_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011/economic_rename.csv'
economic_data.to_csv(new_file_path, index=False)

new_file_path

'C:\\Users\\samuel\\Desktop\\可视化\\教育与劳动力市场\\2011/economic_rename.csv'

In [8]:
# Load the new dataset
new_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011\未处理/hq.csv'
hq_data = pd.read_csv(new_file_path)

# Display the first few rows of the dataset and the columns to understand its structure
hq_data.head(), hq_data.columns

(   date       geography geography code Rural Urban  \
 0  2011        Bank Top      E05001553       Total
 1  2011         Central      E05001554       Total
 2  2011  Cockerton East      E05001555       Total
 3  2011  Cockerton West      E05001556       Total
 4  2011         College      E05001557       Total

    Qualification: All categories: Highest level of qualification; measures: Value  \
 0                                               3342
 1                                               3437
 2                                               4328
 3                                               3187
 4                                               3409

    Qualification: No qualifications; measures: Value  \
 0                                               1087
 1                                               1052
 2                                               1014
 3                                               1134
 4                                                415

    Qualification: Level 1 qualifications; measures: Value  \
 0                                                440
 1                                                490
 2                                                695
 3                                                523
 4                                                293

    Qualification: Level 2 qualifications; measures: Value  \
 0                                                508
 1                                                561
 2                                                727
 3                                                522
 4                                                501

    Qualification: Apprenticeship; measures: Value  \
 0                                             154
 1                                             157
 2                                             270
 3                                             143
 4                                             105

    Qualification: Level 3 qualifications; measures: Value  \
 0                                                440
 1                                                414
 2                                                605
 3                                                343
 4                                                381

    Qualification: Level 4 qualifications and above; measures: Value  \
 0                                                531
 1                                                603
 2                                                855
 3                                                368
 4                                               1624

    Qualification: Other qualifications; measures: Value
 0                                                182
 1                                                160
 2                                                162
 3                                                154
 4                                                 90     ,
 Index(['date', 'geography', 'geography code', 'Rural Urban',
        'Qualification: All categories: Highest level of qualification; measures: Value',
        'Qualification: No qualifications; measures: Value',
        'Qualification: Level 1 qualifications; measures: Value',
        'Qualification: Level 2 qualifications; measures: Value',
        'Qualification: Apprenticeship; measures: Value',
        'Qualification: Level 3 qualifications; measures: Value',
        'Qualification: Level 4 qualifications and above; measures: Value',
        'Qualification: Other qualifications; measures: Value'],
       dtype='object'))

In [9]:
# Simplify the column names for the new dataset
simplified_columns_hq = {
    'date': 'Year',
    'geography': 'Area',
    'geography code': 'Area Code',
    'Rural Urban': 'Rural Urban',
    'Qualification: All categories: Highest level of qualification; measures: Value': 'Total Population',
    'Qualification: No qualifications; measures: Value': 'No Qualifications',
    'Qualification: Level 1 qualifications; measures: Value': 'Level 1 Qualifications',
    'Qualification: Level 2 qualifications; measures: Value': 'Level 2 Qualifications',
    'Qualification: Apprenticeship; measures: Value': 'Apprenticeships',
    'Qualification: Level 3 qualifications; measures: Value': 'Level 3 Qualifications',
    'Qualification: Level 4 qualifications and above; measures: Value': 'Level 4 and Above Qualifications',
    'Qualification: Other qualifications; measures: Value': 'Other Qualifications'
}

# Rename the columns
hq_data.rename(columns=simplified_columns_hq, inplace=True)

# Display the new column names and the first few rows to check
hq_data.head(), hq_data.columns
# Save the cleaned and simplified dataset to a new CSV file for the hq data
new_hq_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011/hq_cleaned.csv'
hq_data.to_csv(new_hq_file_path, index=False)

new_hq_file_path

'C:\\Users\\samuel\\Desktop\\可视化\\教育与劳动力市场\\2011/hq_cleaned.csv'

In [11]:
# Load the new dataset
new_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011\未处理/industry.csv'
industry_data = pd.read_csv(new_file_path)

# Display the first few rows of the dataset and the columns to understand its structure
industry_data.head(), industry_data.columns

(   date       geography geography code Rural Urban  \
 0  2011        Bank Top      E05001553       Total
 1  2011         Central      E05001554       Total
 2  2011  Cockerton East      E05001555       Total
 3  2011  Cockerton West      E05001556       Total
 4  2011         College      E05001557       Total

    Industry: All categories: Industry; measures: Value  \
 0                                               1813
 1                                               1790
 2                                               2655
 3                                               1479
 4                                               2103

    Industry: A Agriculture, forestry and fishing; measures: Value  \
 0                                                  8
 1                                                  4
 2                                                  3
 3                                                  6
 4                                                  1

    Industry: B Mining and quarrying; measures: Value  \
 0                                                  3
 1                                                  4
 2                                                  6
 3                                                  3
 4                                                  9

    Industry: C Manufacturing; measures: Value  \
 0                                         183
 1                                         208
 2                                         265
 3                                         136
 4                                         206

    Industry: C10-12 Manufacturing: Food, beverages and tobacco; measures: Value  \
 0                                                 25
 1                                                 28
 2                                                 19
 3                                                 20
 4                                                 12

    Industry: C13-15 Manufacturing: Textiles, wearing apparel and leather and related products; measures: Value  \
 0                                                  2
 1                                                  6
 2                                                  4
 3                                                  3
 4                                                 10

    ...  Industry: K Financial and insurance activities; measures: Value  \
 0  ...                                                 60
 1  ...                                                 71
 2  ...                                                114
 3  ...                                                 52
 4  ...                                                 90

    Industry: L Real estate activities; measures: Value  \
 0                                                  7
 1                                                 18
 2                                                 23
 3                                                 11
 4                                                 27

    Industry: M Professional, scientific and technical activities; measures: Value  \
 0                                                 58
 1                                                 61
 2                                                 89
 3                                                 33
 4                                                179

    Industry: N Administrative and support service activities; measures: Value  \
 0                                                 80
 1                                                102
 2                                                104
 3                                                 83
 4                                                 57

    Industry: O Public administration and defence; compulsory social security; measures: Value  \
 0                                                113
 1                                                 70
 2                                                223
 3                                                 89
 4                                                183

    Industry: P Education; measures: Value  \
 0                                     102
 1                                     109
 2                                     205
 3                                     108
 4                                     315

    Industry: Q Human health and social work activities; measures: Value  \
 0                                                291
 1                                                235
 2                                                418
 3                                                238
 4                                                334

    Industry: R,S Arts, entertainment and recreation; other service activities; measures: Value  \
 0                                                 62
 1                                                 79
 2                                                 91
 3                                                 69
 4                                                 86

    Industry: T Activities of households as employers; undifferentiated goods - and services - producing activities of households for own use; measures: Value  \
 0                                                  0
 1                                                  2
 2                                                  1
 3                                                  0
 4                                                  1

    Industry: U Activities of extraterritorial organisations and bodies; measures: Value
 0                                                  0
 1                                                  0
 2                                                  0
 3                                                  0
 4                                                  0

 [5 rows x 32 columns],
 Index(['date', 'geography', 'geography code', 'Rural Urban',
        'Industry: All categories: Industry; measures: Value',
        'Industry: A Agriculture, forestry and fishing; measures: Value',
        'Industry: B Mining and quarrying; measures: Value',
        'Industry: C Manufacturing; measures: Value',
        'Industry: C10-12 Manufacturing: Food, beverages and tobacco; measures: Value',
        'Industry: C13-15 Manufacturing: Textiles, wearing apparel and leather and related products; measures: Value',
        'Industry: C16,17 Manufacturing: Wood, paper and paper products; measures: Value',
        'Industry: C19-22 Manufacturing: Chemicals, chemical products, rubber and plastic; measures: Value',
        'Industry: C23-25 Manufacturing: Low tech; measures: Value',
        'Industry: C26-30 Manufacturing: High tech; measures: Value',
        'Industry: C18, 31, 32 Manufacturing: Other; measures: Value',
        'Industry: D Electricity, gas, steam and air conditioning supply; measures: Value',
        'Industry: E Water supply, sewerage, waste management and remediation activities; measures: Value',
        'Industry: F Construction; measures: Value',
        'Industry: G Wholesale and retail trade; repair of motor vehicles and motor cycles; measures: Value',
        'Industry: H Transport and storage; measures: Value',
        'Industry: I Accommodation and food service activities; measures: Value',
        'Industry: J Information and communication; measures: Value',
        'Industry: K Financial and insurance activities; measures: Value',
        'Industry: L Real estate activities; measures: Value',
        'Industry: M Professional, scientific and technical activities; measures: Value',
        'Industry: N Administrative and support service activities; measures: Value',
        'Industry: O Public administration and defence; compulsory social security; measures: Value',
        'Industry: P Education; measures: Value',
        'Industry: Q Human health and social work activities; measures: Value',
        'Industry: R,S Arts, entertainment and recreation; other service activities; measures: Value',
        'Industry: T Activities of households as employers; undifferentiated goods - and services - producing activities of households for own use; measures: Value',
        'Industry: U Activities of extraterritorial organisations and bodies; measures: Value'],
       dtype='object'))

In [13]:
# Given column names from the user, creating a mapping to simplify them
simplified_columns_industry = {
    'date': 'Year',
    'geography': 'Area',
    'geography code': 'Area Code',
    'Rural Urban': 'Rural Urban',
    'Industry: All categories: Industry; measures: Value': 'Total Industry',
    'Industry: A Agriculture, forestry and fishing; measures: Value': 'Agriculture Forestry Fishing',
    'Industry: B Mining and quarrying; measures: Value': 'Mining Quarrying',
    'Industry: C Manufacturing; measures: Value': 'Manufacturing',
    'Industry: C10-12 Manufacturing: Food, beverages and tobacco; measures: Value': 'Manufacturing Food Beverages Tobacco',
    'Industry: C13-15 Manufacturing: Textiles, wearing apparel and leather and related products; measures: Value': 'Manufacturing Textiles Apparel Leather',
    'Industry: C16,17 Manufacturing: Wood, paper and paper products; measures: Value': 'Manufacturing Wood Paper Products',
    'Industry: C19-22 Manufacturing: Chemicals, chemical products, rubber and plastic; measures: Value': 'Manufacturing Chemicals Rubber Plastic',
    'Industry: C23-25 Manufacturing: Low tech; measures: Value': 'Manufacturing Low Tech',
    'Industry: C26-30 Manufacturing: High tech; measures: Value': 'Manufacturing High Tech',
    'Industry: C18, 31, 32 Manufacturing: Other; measures: Value': 'Manufacturing Other',
    'Industry: D Electricity, gas, steam and air conditioning supply; measures: Value': 'Electricity Gas Steam AC Supply',
    'Industry: E Water supply, sewerage, waste management and remediation activities; measures: Value': 'Water Supply Waste Management',
    'Industry: F Construction; measures: Value': 'Construction',
    'Industry: G Wholesale and retail trade; repair of motor vehicles and motor cycles; measures: Value': 'Wholesale Retail Trade',
    'Industry: H Transport and storage; measures: Value': 'Transport Storage',
    'Industry: I Accommodation and food service activities; measures: Value': 'Accommodation Food Services',
    'Industry: J Information and communication; measures: Value': 'Information Communication',
    'Industry: K Financial and insurance activities; measures: Value': 'Financial Insurance Activities',
    'Industry: L Real estate activities; measures: Value': 'Real Estate Activities',
    'Industry: M Professional, scientific and technical activities; measures: Value': 'Professional Scientific Technical Activities',
    'Industry: N Administrative and support service activities; measures: Value': 'Administrative Support Services',
    'Industry: O Public administration and defence; compulsory social security; measures: Value': 'Public Administration Defence',
    'Industry: P Education; measures: Value': 'Education',
    'Industry: Q Human health and social work activities; measures: Value': 'Health Social Work Activities',
    'Industry: R,S Arts, entertainment and recreation; other service activities; measures: Value': 'Arts Entertainment Recreation',
    'Industry: T Activities of households as employers; undifferentiated goods - and services - producing activities of households for own use; measures: Value': 'Household Activities',
    'Industry: U Activities of extraterritorial organisations and bodies; measures: Value': 'Extraterritorial Organisations Activities'
}

# Rename the columns
industry_data.rename(columns=simplified_columns_industry, inplace=True)

# Display the new column names and the first few rows to check
industry_data.head(), hq_data.columns
# Save the cleaned and simplified dataset to a new CSV file for the hq data
new_industry_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011/industry_rename.csv'
industry_data.to_csv(new_industry_file_path, index=False)
new_industry_file_path

'C:\\Users\\samuel\\Desktop\\可视化\\教育与劳动力市场\\2011/industry_rename.csv'

In [19]:
# Load the new dataset
new_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011\未处理/occupation.csv'
occupation_data = pd.read_csv(new_file_path)

# Map the provided column names to simplified ones
simplified_columns_occupation = {
    'date': 'Year',
    'geography': 'Area',
    'geography code': 'Area Code',
    'Rural Urban': 'Rural Urban',
    'Occupation: All categories: Occupation; measures: Value': 'Total Occupation',
    'Occupation: 1. Managers, directors and senior officials; measures: Value': 'Managers Directors Senior Officials',
    'Occupation: 11. Corporate managers and directors; measures: Value': 'Corporate Managers Directors',
    'Occupation: 111. Chief Executives and Senior Officials; measures: Value': 'Chief Executives Senior Officials',
    'Occupation: 112. Production Managers and Directors; measures: Value': 'Production Managers Directors',
    'Occupation: 113. Functional Managers and Directors; measures: Value': 'Functional Managers Directors',
    'Occupation: 115. Financial Institution Managers and Directors; measures: Value': 'Financial Institution Managers Directors',
    'Occupation: 116. Managers and Directors in Transport and Logistics; measures: Value': 'Managers Directors Transport Logistics',
    'Occupation: 117. Senior Officers in Protective Services; measures: Value': 'Senior Officers Protective Services',
    'Occupation: 118. Health and Social Services Managers and Directors; measures: Value': 'Health Social Services Managers Directors',
    'Occupation: 119. Managers and Directors in Retail and Wholesale; measures: Value': 'Managers Directors Retail Wholesale',
    'Occupation: 12. Other managers and proprietors; measures: Value': 'Other Managers Proprietors',
    'Occupation: 121. Managers and Proprietors in Agriculture Related Services; measures: Value': 'Managers Proprietors Agriculture Services',
    'Occupation: 122. Managers and Proprietors in Hospitality and Leisure Services; measures: Value': 'Managers Proprietors Hospitality Leisure Services',
    'Occupation: 124. Managers and Proprietors in Health and Care Services; measures: Value': 'Managers Proprietors Health Care Services',
    'Occupation: 125. Managers and Proprietors in Other Services; measures: Value': 'Managers Proprietors Other Services',
    'Occupation: 2. Professional occupations; measures: Value': 'Professional Occupations',
    'Occupation: 21. Science research, engineering and technology professionals; measures: Value': 'Science Research Engineering Technology Professionals',
    'Occupation: 211. Natural and Social Science Professionals; measures: Value': 'Natural Social Science Professionals',
    'Occupation: 212. Engineering Professionals; measures: Value': 'Engineering Professionals',
    'Occupation: 213. Information Technology and Telecommunications Professionals; measures: Value': 'IT Telecommunications Professionals',
    'Occupation: 214. Conservation and Environment Professionals; measures: Value': 'Conservation Environment Professionals',
    'Occupation: 215. Research and Development Managers; measures: Value': 'Research Development Managers',
    'Occupation: 22. Health professionals; measures: Value': 'Health Professionals',
    'Occupation: 221. Health Professionals; measures: Value': 'Health Professionals',
    'Occupation: 222. Therapy Professionals; measures: Value': 'Therapy Professionals',
    'Occupation: 223. Nursing and Midwifery Professionals; measures: Value': 'Nursing Midwifery Professionals',
    'Occupation: 23. Teaching and educational professionals; measures: Value': 'Teaching Educational Professionals',
    'Occupation: 231. Teaching and Educational Professionals; measures: Value': 'Teaching Educational Professionals',
    'Occupation: 24. Business, media and public service professionals; measures: Value': 'Business Media Public Service Professionals',
    'Occupation: 241. Legal Professionals; measures: Value': 'Legal Professionals',
    'Occupation: 242. Research and Administrative Professionals; measures: Value': 'Research Administrative Professionals',
    'Occupation: 243. Architects, Town Planners and Surveyors; measures: Value': 'Architects Town Planners Surveyors',
    'Occupation: 244. Welfare Professionals; measures: Value': 'Welfare Professionals',
    'Occupation: 245. Librarians and Related Professionals; measures: Value': 'Librarians Related Professionals',
    'Occupation: 246. Quality and Regulatory Professionals; measures: Value': 'Quality Regulatory Professionals',
    'Occupation: 247. Media Professionals; measures: Value': 'Media Professionals',
    'Occupation: 3. Associate professional and technical occupations; measures: Value': 'Associate Professional Technical Occupations',
    'Occupation: 31. Science, engineering and technology associate professionals; measures: Value': 'Science Engineering Technology Associate Professionals',
    'Occupation: 311. Science, Engineering and Production Technicians; measures: Value': 'Science Engineering Production Technicians',
    'Occupation: 312. Draughtspersons and Related Architectural Technicians; measures: Value': 'Draughtspersons Related Architectural Technicians',
    'Occupation: 313. Information Technology Technicians; measures: Value': 'IT Technicians',
    'Occupation: 32. Health and social care associate professionals; measures: Value': 'Health Social Care Associate Professionals',
    'Occupation: 321. Health Associate Professionals; measures: Value': 'Health Associate Professionals',
    'Occupation: 323. Welfare and Housing Associate Professionals; measures: Value': 'Welfare Housing Associate Professionals',
    'Occupation: 33. Protective Service Occupations; measures: Value': 'Protective Service Occupations',
    'Occupation: 331. Protective Service Occupations; measures: Value': 'Protective Service Occupations',
    'Occupation: 34. Culture, media and sports occupations; measures: Value': 'Culture Media Sports Occupations',
    'Occupation: 341. Artistic, Literary and Media Occupations; measures: Value': 'Artistic Literary Media Occupations',
    'Occupation: 342. Design Occupations; measures: Value': 'Design Occupations',
    'Occupation: 344. Sports and Fitness Occupations; measures: Value': 'Sports Fitness Occupations',
    'Occupation: 35. Business and public service associate professionals; measures: Value': 'Business Public Service Associate Professionals',
    'Occupation: 351. Transport Associate Professionals; measures: Value': 'Transport Associate Professionals',
    'Occupation: 352. Legal Associate Professionals; measures: Value': 'Legal Associate Professionals',
    'Occupation: 353. Business, Finance and Related Associate Professionals; measures: Value': 'Business Finance Related Associate Professionals',
    'Occupation: 354. Sales, Marketing and Related Associate Professionals; measures: Value': 'Sales Marketing Related Associate Professionals',
    'Occupation: 355. Conservation and Environmental associate professionals; measures: Value': 'Conservation Environmental Associate Professionals',
    'Occupation: 356. Public Services and Other Associate Professionals; measures: Value': 'Public Services Other Associate Professionals',
    'Occupation: 4. Administrative and secretarial occupations; measures: Value': 'Administrative Secretarial Occupations',
    'Occupation: 41. Administrative occupations; measures: Value': 'Administrative Occupations',
    'Occupation: 411. Government and Related Organisations; measures: Value': 'Government Related Organisations',
    'Occupation: 412. Finance; measures: Value': 'Finance Occupations',
    'Occupation: 413. Records; measures: Value': 'Records Occupations',
    'Occupation: 415. Other Administrative Occupations; measures: Value': 'Other Administrative Occupations',
    'Occupation: 416. Office Managers and Supervisors; measures: Value': 'Office Managers Supervisors',
    'Occupation: 42. Secretarial and related occupations; measures: Value': 'Secretarial Related Occupations',
    'Occupation: 421. Secretarial and Related Occupations; measures: Value': 'Secretarial Related Occupations',
    'Occupation: 5. Skilled trades occupations; measures: Value': 'Skilled Trades Occupations',
    'Occupation: 51. Skilled agricultural and related trades; measures: Value': 'Skilled Agricultural Related Trades',
    'Occupation: 511. Agricultural and Related Trades; measures: Value': 'Agricultural Related Trades',
    'Occupation: 52. Skilled metal, electrical and electronic trades; measures: Value': 'Skilled Metal Electrical Electronic Trades',
    'Occupation: 521. Metal Forming, Welding and Related Trades; measures: Value': 'Metal Forming Welding Related Trades',
    'Occupation: 522. Metal Machining, Fitting and Instrument Making Trades; measures: Value': 'Metal Machining Fitting Instrument Making Trades',
    'Occupation: 523. Vehicle Trades; measures: Value': 'Vehicle Trades',
    'Occupation: 524. Electrical and Electronic Trades; measures: Value': 'Electrical Electronic Trades',
    'Occupation: 525. Skilled Metal, Electrical and Electronic Trades Supervisors; measures: Value': 'Skilled Metal Electrical Electronic Trades Supervisors',
    'Occupation: 53. Skilled construction and building trades; measures: Value': 'Skilled Construction Building Trades',
    'Occupation: 531. Construction and Building Trades; measures: Value': 'Construction Building Trades',
    'Occupation: 532. Building Finishing Trades; measures: Value': 'Building Finishing Trades',
    'Occupation: 533. Construction and Building Trades Supervisors; measures: Value': 'Construction Building Trades Supervisors',
    'Occupation: 54. Textiles, printing and other skilled trades; measures: Value': 'Textiles Printing Other Skilled Trades',
    'Occupation: 541. Textiles and Garments Trades; measures: Value': 'Textiles Garments Trades',
    'Occupation: 542. Printing Trades; measures: Value': 'Printing Trades',
    'Occupation: 543. Food Preparation and Hospitality Trades; measures: Value': 'Food Preparation Hospitality Trades',
    'Occupation: 544. Other Skilled Trades; measures: Value': 'Other Skilled Trades',
    'Occupation: 6. Caring, leisure and other service occupations; measures: Value': 'Caring Leisure Other Service Occupations',
    'Occupation: 61. Caring personal service occupations; measures: Value': 'Caring Personal Service Occupations',
    'Occupation: 612. Childcare and Related Personal Services; measures: Value': 'Childcare Related Personal Services',
    'Occupation: 613. Animal Care and Control Services; measures: Value': 'Animal Care Control Services',
    'Occupation: 614. Caring Personal Services; measures: Value': 'Caring Personal Services',
    'Occupation: 62. Leisure, travel and related personal service occupations; measures: Value': 'Leisure Travel Related Personal Service Occupations',
    'Occupation: 621. Leisure and Travel Services; measures: Value': 'Leisure Travel Services',
    'Occupation: 622. Hairdressers and Related Services; measures: Value': 'Hairdressers Related Services',
    'Occupation: 623. Housekeeping and Related Services; measures: Value': 'Housekeeping Related Services',
    'Occupation: 624. Cleaning and Housekeeping Managers and Supervisors; measures: Value': 'Cleaning Housekeeping Managers Supervisors',
    'Occupation: 7. Sales and customer service occupations; measures: Value': 'Sales Customer Service Occupations',
    'Occupation: 71. Sales occupations; measures: Value': 'Sales Occupations',
    'Occupation: 711. Sales Assistants and Retail Cashiers; measures: Value': 'Sales Assistants Retail Cashiers',
    'Occupation: 712. Sales Related Occupations; measures: Value': 'Sales Related Occupations',
    'Occupation: 713. Sales Supervisors; measures: Value': 'Sales Supervisors',
    'Occupation: 72. Customer service occupations; measures: Value': 'Customer Service Occupations',
    'Occupation: 721. Customer Service Occupations; measures: Value': 'Customer Service Occupations',
    'Occupation: 722. Customer Service Managers and Supervisors; measures: Value': 'Customer Service Managers Supervisors',
    'Occupation: 8. Process, plant and machine operatives; measures: Value': 'Process Plant Machine Operatives',
    'Occupation: 81. Process, plant and machine operatives; measures: Value': 'Process Plant Machine Operatives',
    'Occupation: 811. Process Operatives; measures: Value': 'Process Operatives',
    'Occupation: 812. Plant and Machine Operatives; measures: Value': 'Plant Machine Operatives',
    'Occupation: 813. Assemblers and Routine Operatives; measures: Value': 'Assemblers Routine Operatives',
    'Occupation: 814. Construction Operatives; measures: Value': 'Construction Operatives',
    'Occupation: 82. Transport and mobile machine drivers and operatives; measures: Value': 'Transport Mobile Machine Drivers Operatives',
    'Occupation: 821. Road Transport Drivers; measures: Value': 'Road Transport Drivers',
    'Occupation: 822. Mobile Machine Drivers and Operatives; measures: Value': 'Mobile Machine Drivers Operatives',
    'Occupation: 823. Other Drivers and Transport Operatives; measures: Value': 'Other Drivers Transport Operatives',
    'Occupation: 9. Elementary occupations; measures: Value': 'Elementary Occupations',
    'Occupation: 91. Elementary trades and related occupations; measures: Value': 'Elementary Trades Related Occupations',
    'Occupation: 911. Elementary Agricultural Occupations; measures: Value': 'Elementary Agricultural Occupations',
    'Occupation: 912. Elementary Construction Occupations; measures: Value': 'Elementary Construction Occupations',
    'Occupation: 913. Elementary Process Plant Occupations; measures: Value': 'Elementary Process Plant Occupations',
    'Occupation: 92. Elementary administration and service occupations; measures: Value': 'Elementary Administration Service Occupations',
    'Occupation: 921. Elementary Administration Occupations; measures: Value': 'Elementary Administration Occupations',
    'Occupation: 923. Elementary Cleaning Occupations; measures: Value': 'Elementary Cleaning Occupations',
    'Occupation: 924. Elementary Security Occupations; measures: Value': 'Elementary Security Occupations',
    'Occupation: 925. Elementary Sales Occupations; measures: Value': 'Elementary Sales Occupations',
    'Occupation: 926. Elementary Storage Occupations; measures: Value': 'Elementary Storage Occupations',
    'Occupation: 927. Other Elementary Services Occupations; measures: Value': 'Other Elementary Services Occupations'
}


# Rename the columns
occupation_data.rename(columns=simplified_columns_industry, inplace=True)

# Display the new column names and the first few rows to check
occupation_data.head(), hq_data.columns
# Save the cleaned and simplified dataset to a new CSV file for the hq data
new_occupation_file_path = r'C:\Users\samuel\Desktop\可视化\教育与劳动力市场\2011/Occupation_rename.csv'
industry_data.to_csv(new_occupation_file_path, index=False)
new_occupation_file_path

'C:\\Users\\samuel\\Desktop\\可视化\\教育与劳动力市场\\2011/Occupation_rename.csv'